insert into product(sctg_no, manufac_no, name) values(1,2,'애플스마트폰 임시값1');
insert into product(sctg_no, manufac_no, name) values(1,2,'애플스마트폰 임시값2');
insert into product(sctg_no, manufac_no, name) values(2,2,'애플태블릿 임시값1');
insert into product(sctg_no, manufac_no, name) values(2,2,'애플태블릿 임시값2');
insert into product(sctg_no, manufac_no, name) values(3,2,'애플스마트워치 임시값1');
insert into product(sctg_no, manufac_no, name) values(3,2,'애플스마트워치 임시값2');
insert into product(sctg_no, manufac_no, name) values(4,2,'애플악세사리 임시값1');
insert into product(sctg_no, manufac_no, name) values(4,2,'애플악세사리 임시값2');
insert into product(sctg_no, manufac_no, name) values(5,2,'애플노트북 임시값1');
insert into product(sctg_no, manufac_no, name) values(5,2,'애플노트북 임시값2');
insert into product(sctg_no, manufac_no, name) values(6,2,'애플데스크탑 임시값1');
insert into product(sctg_no, manufac_no, name) values(6,2,'애플데스크탑 임시값2');
insert into product(sctg_no, manufac_no, name) values(7,2,'애플 PC부품 임시값1');
insert into product(sctg_no, manufac_no, name) values(7,2,'애플 PC부품 임시값2');
insert into product(sctg_no, manufac_no, name) values(8,2,'애플 PC저장장치 임시값1');
insert into product(sctg_no, manufac_no, name) values(8,2,'애플 PC저장장치 임시값2');
insert into product(sctg_no, manufac_no, name) values(9,2,'애플 디카 임시값1');
insert into product(sctg_no, manufac_no, name) values(9,2,'애플 디카 임시값2');
insert into product(sctg_no, manufac_no, name) values(10,2,'애플 캠코더 임시값1');
insert into product(sctg_no, manufac_no, name) values(10,2,'애플 캠코더 임시값2');
insert into product(sctg_no, manufac_no, name) values(11,2,'애플 카메라렌즈 임시값1');
insert into product(sctg_no, manufac_no, name) values(11,2,'애플 카메라렌즈 임시값2');
insert into product(sctg_no, manufac_no, name) values(12,2,'애플 카메라저장 임시값1');
insert into product(sctg_no, manufac_no, name) values(12,2,'애플 카메라저장 임시값2');
insert into product(sctg_no, manufac_no, name) values(13,2,'애플 세탁기 임시값1');
insert into product(sctg_no, manufac_no, name) values(13,2,'애플 세탁기 임시값2');
insert into product(sctg_no, manufac_no, name) values(14,2,'애플 TV 임시값1');
insert into product(sctg_no, manufac_no, name) values(14,2,'애플 TV 임시값2');
insert into product(sctg_no, manufac_no, name) values(15,2,'애플 냉장고 임시값1');
insert into product(sctg_no, manufac_no, name) values(15,2,'애플 냉장고 임시값2');
insert into product(sctg_no, manufac_no, name) values(16,2,'애플 에어컨 임시값1');
insert into product(sctg_no, manufac_no, name) values(16,2,'애플 에어컨 임시값2');